branch-defaults:
  main:
    environment: udacity-cloud-image-project-dev
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: udacity-cloud-image-project
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
